config/routes.rb
Rails.application.routes.draw do

  rutarel = ENV.fetch('RUTA_RELATIVA', '/')
  scope rutarel do 
    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'
      # El siguiente para superar mala generación del action en el formulario
      # cuando se autentica mal y esta montado no en / (genera 
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/') 
        ruta = File.join(Rails.configuration.relative_url_root, 
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
        get  ruta, to: 'devise/sessions#new'
      end
    end
    devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit', 
        :as => 'editar_registro_usuario'    
      put 'usuarios/:id' => 'devise/registrations#update', 
        :as => 'registro_usuario'            
    end
    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 


    patch "/actos/agregar" => 'sivel2_sjr/actos#agregar',
      as: :actos_agregar
    get "/actos/eliminar" => 'sivel2_sjr/actos#eliminar',
      as: :actos_eliminar
    patch "/actos/agregarpr" => 'sivel2_sjr/actos#nuevopr',
      as: :actos_nuevopr

    # No se requiere edición
    resources :clavesrespaldos, path_names: { new: 'nueva' },
      controller: 'sip/clavesrespaldos'

    get "/conteos/accionesjuridicas" => 'sivel2_sjr/conteos#accionesjuridicas', 
      as: :conteos_accionesjuridicas
    get "/conteos/desplazamientos" => 'sivel2_sjr/conteos#desplazamientos', 
      as: :conteos_desplazamientos
    get "/conteos/municipios" => 'sivel2_sjr/conteos#municipios', 
      as: :conteos_municipios
    get "/conteos/rutas" => 'sivel2_sjr/conteos#rutas', 
      as: :contes_rutas
    get "/conteos/vacios" => 'sivel2_sjr/conteos#vacios',
      as: :conteos_vacios

    get '/migraciones/nuevo' => 'sivel2_sjr/migraciones#nuevo'  

    #get "/personas" => 'sip/personas#index'
    #get "/personas/remplazar" => 'sip/personas#remplazar'

    get "/casos/:id/fichaimp" => "sivel2_sjr/casos#fichaimp",
      as: :caso_fichaimp

    get "/casos/:id/fichapdf" => "sivel2_sjr/casos#fichapdf",
      as: :caso_fichapdf

    get '/personas_casos' => 'sivel2_sjr/casos#personas_casos',
      as: :personas_casos

    get '/ubicacionespre' => 'sip/ubicacionespre#index',
      as: :ubicacionespre
    get '/ubicacionespre_mundep' => 'sip/ubicacionespre#mundep',
      as: :ubicacionespre_mundep
    get '/ubicacionespre_lugar' => 'sip/ubicacionespre#lugar',
      as: :ubicacionespre_lugar

    get '/actividadespf/nueva' => 'cor1440_gen/actividadespf#new',
      as: :nueva_actividadespf

    get '/actividadespf/:id' => 'cor1440_gen/actividadespf#show',
      as: :show_actividadespf

    get '/actividadespflistado' => 'cor1440_gen/actividadespf#index',
      as: :index_actividadespf

    get '/asistencia/nueva' => 'cor1440_gen/actividades#nueva_asistencia',
      as: :nueva_asistencia

    get '/consgifmm' => 'consgifmm#index',
      as: :consgifmm

    get '/detallesfinancieros/nuevo' => 'detallesfinancieros#nuevo'

    get '/revisaben_detalle' => 'cor1440_gen/actividades#revisaben_detalle'

    root "sip/hogar#index"

    namespace :admin do
      ab = ::Ability.new
      ab.tablasbasicas.each do |t|
        if (t[0] == "") 
          c = t[1].pluralize
          resources c.to_sym, 
            path_names: { new: 'nueva', edit: 'edita' }
        end
      end
    end
  end

  mount Sivel2Sjr::Engine, at: rutarel, as: 'sivel2_sjr'
  mount Sivel2Gen::Engine, at: rutarel, as: 'sivel2_gen'
  mount Cor1440Gen::Engine, at: rutarel, as: 'cor1440_gen'
  mount Sal7711Gen::Engine, at: rutarel, as: 'sal7711_gen'
  mount Mr519Gen::Engine, at: rutarel, as: 'mr519_gen'
  mount Heb412Gen::Engine, at: rutarel, as: 'heb412_gen'
  mount Sip::Engine, at: rutarel, as: 'sip'

end

app/models/sivel2_gen/caso.rb
# encoding: UTF-8

require 'sivel2_sjr/concerns/models/caso'
class Sivel2Gen::Caso < ActiveRecord::Base
  include Sivel2Sjr::Concerns::Models::Caso

  def presenta(atr)
    case atr.to_s
    when 'fecharec'
      casosjr.fecharec if casosjr.fecharec
    when 'oficina'
      casosjr.oficina.nombre if casosjr.oficina
    when 'asesor'
      casosjr.usuario.nusuario if casosjr.usuario
    when 'contacto'
      if casosjr && casosjr.contacto
        casosjr.contacto.nombres + ' ' + casosjr.contacto.apellidos +
       ' ' + ((casosjr.contacto.tdocumento.nil? ||
               casosjr.contacto.tdocumento.sigla.nil?) ? '' : 
              casosjr.contacto.tdocumento.sigla) + ' ' +
       ' ' + (casosjr.contacto.numerodocumento.nil? ? '' : 
              casosjr.contacto.numerodocumento)
      end
    when 'direccion'
      casosjr.direccion if casosjr.direccion
    when 'telefono'
      casosjr.telefono if casosjr.telefono
    else
      presenta_gen(atr) 
    end
  end

  has_many :migracion, class_name: 'Sivel2Sjr::Migracion',
    foreign_key: "caso_id", validate: true, dependent: :destroy
  accepts_nested_attributes_for :migracion, allow_destroy: true, 
    reject_if: :all_blank

end

app/controllers/sivel2_sjr/casos_controller.rb
# encoding: UTF-8

require_dependency 'sivel2_sjr/concerns/controllers/casos_controller'
require_dependency 'heb412_gen/docs_controller'

module Sivel2Sjr
  class CasosController < Heb412Gen::ModelosController

    include Sivel2Sjr::Concerns::Controllers::CasosController

    before_action :set_caso, only: [:show, :edit, :update, :destroy],
      exclude: [:poblacion_sexo_rangoedadac, :personas_casos]
    load_and_authorize_resource class: Sivel2Gen::Caso

    def vistas_manejadas
      ['Caso']
    end

    def atributos_show
      [
        # basicos
        :id,
        :fecharec,
        :oficina,
        :fecha,
        :memo,
        :created_at,
        :asesor,
        :contacto,
        :direccion,
        :telefono,
        :atenciones,
        :listado_familiares,
        :listado_anexos
      ]
    end

    # Campos en filtro
    def campos_filtro1
      [
        :apellidos, 
        :apellidossp, 
        :atenciones_fechaini,
        :atenciones_fechafin,
        :categoria_id,
        :codigo,
        :departamento_id,
        :descripcion,
        :expulsion_pais_id, 
        :expulsion_departamento_id, 
        :expulsion_municipio_id,
        :fechaini, 
        :fechafin, 
        :fecharecini, 
        :fecharecfin, 
        :llegada_pais_id, 
        :llegada_departamento_id, 
        :llegada_municipio_id,
        :nombressp, 
        :numerodocumento,
        :nombres, 
        :oficina_id, 
        :rangoedad_id, 
        :sexo, 
        :tdocumento, 
        :ultimaatencion_fechaini, 
        :ultimaatencion_fechafin,
        :usuario_id,
      ]
    end

    # Campos por presentar en listado index
    def incluir_inicial
      return ['casoid', 'contacto', 'fecharec', 'oficina', 
              'nusuario', 'fecha', 'expulsion',
              'llegada', 'ultimaatencion_fecha', 'memo'
      ]
    end

    # Ordenamiento inicial por este campo
    def campoord_inicial
      'fecharec'
    end

    def asegura_camposdinamicos(registro, current_usuario_id)
    end


    # Responde con mensaje de error
    def resp_error(m)
      respond_to do |format|
        format.html { 
          render inline: m
        }
        format.json { 
          render json: m, status: :unprocessable_entity 
        }
      end
    end

    # Fución API que retorna personas de un caso
    def personas_casos
      authorize! :read, Sip::Persona
      res = []
      if params && params['caso_ids']
        puts "params es #{params.inspect}"
        params['caso_ids'].split(',').each do |cc|
          nc = cc.to_i
          if Sivel2Gen::Caso.where(id: nc).count == 0
            resp_error("No se encontró caso #{nc}")
            return
          end
          c = Sivel2Gen::Caso.find(nc)
          c.persona.each do |p|
            res.push({
              persona_id: p.id,
              nombres: p.nombres,
              apellidos: p.apellidos,
              tdocumento_sigla: p.tdocumento ? p.tdocumento.sigla : '',
              numerodocumento: p.numerodocumento
            })
          end
        end
      end

      resj = res.to_json
      respond_to do |format|
        format.js { render text: resj }
        format.json { render json: resj, status: :created }
        format.html { render inline: resj }
      end

    end

    def filtrar_ca(conscaso)
      if current_usuario && current_usuario.rol == Ability::ROLINV
        aeu = current_usuario.etiqueta_usuario.map { |eu| eu.etiqueta_id }
        conscaso = conscaso.joins(
          'JOIN sivel2_gen_caso_etiqueta as cet ON cet.id_caso=id_caso')
        if aeu.count == 0
          conscaso = conscaso.where('FALSE')
        else
          conscaso = conscaso.where('cet.id_etiqueta IN [?]', aeu.join(','))
        end
      end
      return conscaso
    end

    # Tipo de reporte Resolución 1612
    def filtro_particular(conscaso, params_filtro)
      if (params_filtro['dispresenta'] == 'tabla1612') 
        @incluir =  [
          'casoid', 'tipificacion', 'victimas', 'fechadespemb', 
          'ubicaciones', 'presponsables', 'descripcion', 'memo1612'
        ]
        conscaso = conscaso.where('caso_id in (SELECT id_caso 
                                        FROM public.sivel2_gen_acto
                                        WHERE id_categoria = 3020
                                        OR id_categoria=3021)')
        @usa_consexpcaso = true
        Sivel2Gen::Consexpcaso.crea_consexpcaso(conscaso)

        @consexpcaso = Sivel2Gen::Consexpcaso.all
      end
      return conscaso
    end

    def update
      # Procesar ubicacionespre de migración
      (caso_params[:migracion_attributes] || []).each do |clave, mp|
        mi = Sivel2Sjr::Migracion.find(mp[:id].to_i)
        mi.salidaubicacionpre_id = Sip::Ubicacionpre::buscar_o_agregar(
          mp[:salida_pais_id], mp[:salida_departamento_id],
          mp[:salida_municipio_id], mp[:salida_clase_id],
          mp[:salida_lugar], mp[:salida_sitio], mp[:salida_tsitio_id],
          mp[:salida_latitud], mp[:salida_longitud]
        )
        mi.llegadaubicacionpre_id = Sip::Ubicacionpre::buscar_o_agregar(
          mp[:llegada_pais_id], mp[:llegada_departamento_id],
          mp[:llegada_municipio_id], mp[:llegada_clase_id],
          mp[:llegada_lugar], mp[:llegada_sitio], mp[:llegada_tsitio_id],
          mp[:llegada_latitud], mp[:llegada_longitud]
        )
        mi.destinoubicacionpre_id = Sip::Ubicacionpre::buscar_o_agregar(
          mp[:destino_pais_id], mp[:destino_departamento_id],
          mp[:destino_municipio_id], mp[:destino_clase_id],
          mp[:destino_lugar], mp[:destino_sitio], mp[:destino_tsitio_id],
          mp[:destino_latitud], mp[:destino_longitud]
        )
        mi.save!
      end

      (caso_params[:desplazamiento_attributes] || []).each do |clave, dp|
        de = Sivel2Sjr::Desplazamiento.find(dp[:id].to_i)
        de.expulsionubicacionpre_id = Sip::Ubicacionpre::buscar_o_agregar(
          dp[:expulsion_pais_id], dp[:expulsion_departamento_id],
          dp[:expulsion_municipio_id], dp[:expulsion_clase_id],
          dp[:expulsion_lugar], dp[:expulsion_sitio], dp[:expulsion_tsitio_id],
          dp[:expulsion_latitud], dp[:expulsion_longitud]
        )
        de.llegadaubicacionpre_id = Sip::Ubicacionpre::buscar_o_agregar(
          dp[:llegada_pais_id], dp[:llegada_departamento_id],
          dp[:llegada_municipio_id], dp[:llegada_clase_id],
          dp[:llegada_lugar], dp[:llegada_sitio], dp[:llegada_tsitio_id],
          dp[:llegada_latitud], dp[:llegada_longitud]
        )
        de.destinoubicacionpre_id = Sip::Ubicacionpre::buscar_o_agregar(
          dp[:destino_pais_id], dp[:destino_departamento_id],
          dp[:destino_municipio_id], dp[:destino_clase_id],
          dp[:destino_lugar], dp[:destino_sitio], dp[:destino_tsitio_id],
          dp[:destino_latitud], dp[:destino_longitud]
        )
        de.save!
      end
      
      # Convertir valores de radios tri-estado, el valor 3 en el 
      # botón de radio es nil en la base de datos
      if params && params[:caso] && params[:caso][:victima_attributes]
        params[:caso][:victima_attributes].each do |l, v|
          [:actualtrabajando, :asisteescuela, 
           :cabezafamilia, :tienesisben].each do |sym|
            if v[:victimasjr_attributes] && v[:victimasjr_attributes][sym] && v[:victimasjr_attributes][sym] == '3'
              v[:victimasjr_attributes][sym] = nil
            end
          end
        end
      end
      update_sivel2_sjr
    end

    def destroy
      if @caso.casosjr.respuesta
        # No se logró hacer ni con dependente:destroy en
        # las relaciones ni borrando con delete 
        @caso.casosjr.respuesta.each do |r|
          Sivel2Sjr::AccionjuridicaRespuesta.where(respuesta_id: r.id).
            delete_all
        end
      end
      sivel2_sjr_destroy
    end

    def otros_params_respuesta
      [
        :accionjuridica_respuesta_attributes => [
          :accionjuridica_id,
          :favorable,
          :id,
          :_destroy
        ]
      ]
    end

    def otros_params_victimasjr 
      [ :actualtrabajando, :discapacidad_id ]
    end

    def otros_params_victima
      [:anexo_victima_attributes => [
        :fecha_localizada,
        :tipoanexo_id,
        :id, 
        :id_victima,
        :_destroy,
        :sip_anexo_attributes => [
          :adjunto, 
          :descripcion, 
          :id, 
          :_destroy
        ]
      ] ]
    end

    def otros_params
      [
        :migracion_attributes => [
          :actor_pago,
          :autoridadrefugio_id,
          :causaRefugio_id,
          :causamigracion_id,
          :concepto_pago,
          :destino_clase_id,
          :destino_departamento_id,
          :destino_municipio_id,
          :destino_pais_id,
          :destino_latitud,
          :destino_longitud,
          :destino_lugar,
          :destino_sitio,
          :destino_tsitio_id,
          :fechallegada,
          :fechaNpi,
          :fechaPep,
          :fechasalida,
          :fechaendestino,
          :id,
          :llegada_clase_id,
          :llegada_departamento_id,
          :llegada_municipio_id,
          :llegada_pais_id,
          :llegada_latitud,
          :llegada_longitud,
          :llegada_lugar,
          :llegada_sitio,
          :llegada_tsitio_id,
          :llegada_ubicacionpre_id,
          :miembrofamiliar_id,
          :migracontactopre_id,
          :observacionesref,
          :otraagresion,
          :otraautoridad,
          :otracausa,
          :otromiembro,
          :otracausagrpais,
          :otracausaagresion,
          :otronpi,
          :pagoingreso_id,
          :pep,
          :perpeagresenpais,
          :perpetradoresagresion,
          :perfilmigracion_id,
          :proteccion_id,
          :salida_pais_id,
          :salida_departamento_id,
          :salida_municipio_id,
          :salida_clase_id,
          :salida_latitud,
          :salida_longitud,

app/views/casos/_contacto_fields.html.erb
<%= f.simple_fields_for :persona do |p| %>
	<%= render 'persona_fields', :f => p %>
<% end %>
<%= f.association :rangoedad,
	include_blank: false,
	label: "Rango de Edad",
	label_method: :rango, 
	value_method: :id 
%>
<%= f.association :filiacion,
	collection: Filiacion.all.order(:nombre),
	include_blank: false,
	label: "Filiación",
	label_method: :nombre, 
	value_method: :id 
%>
<%= f.association :organizacion,
	collection: Organizacion.all.order(:nombre),
	include_blank: false,
	label: "Organización",
	label_method: :nombre, 
	value_method: :id 
%>
<%= f.association :vinculoestado,
	collection: Vinculoestado.all.order(:nombre),
	include_blank: false,
	label: "Vínculo con el Estado",
	label_method: :nombre, 
	value_method: :id
%>
<%= f.association :etnia,
	collection: Etnia.all.order(:nombre),
	include_blank: false,
	label: "Etnia",
	label_method: :nombre, 
	value_method: :id 
%>
<%= f.input(:orientacionsexual, collection: [
						[:HETEROSEXUAL, :H], [:LESBIANA, :L], [:GAY, :G], 
						[:BISEXUAL, :B], [:TRANSEXUAL, :T] 
], 
	label: "Orientación Sexual",
	include_blank: false ) 
%>

<%= f.input :anotaciones %>

<%= f.association :profesion,
	collection: Profesion.all.order(:nombre),
	include_blank: false,
	label: "Profesión",
	label_method: :nombre, 
	value_method: :id 
%>

<%= f.input :id, as: :hidden %>

<%= f.simple_fields_for :victimasjr do |s| %>
	<%= s.association :estadocivil,
		collection: Estadocivil.all.order(:nombre),
		include_blank: false,
		label: "Estado Civil",
		label_method: :nombre, 
		value_method: :id 
	%>
	<%= s.association :rolfamilia,
		collection: Rolfamilia.all.order(:nombre),
		include_blank: false,
		label: "Rol en Familia",
		label_method: :nombre, 
		value_method: :id 
  %>

  <%= s.input :sindocumento, 
    boolean_style: :nested, 
    inline_label: "Sin Doc. Identidad" %>
  <%= s.input :cabezafamilia, 
    boolean_style: :nested, 
    inline_label: "Cabeza de Familia"
  %>
	<%= s.association :maternidad,
		collection: Maternidad.all.order(:nombre),
		label: "Maternidad",
		label_method: :nombre, 
		value_method: :id 
  %>	
	<%= s.association :actividadoficio,
		collection: Actividadoficio.all.order(:nombre),
		include_blank: false,
		label: "Actividad/Oficio actual",
		label_method: :nombre, 
    value_method: :id,
    wrapper_html: { style: "padding-bottom: 18px;" }
	%>
	<%= s.association :escolaridad,
		collection: Escolaridad.all.order(:nombre),
		include_blank: false,
		label: "Nivel Escolar",
		label_method: :nombre, 
		value_method: :id
  %>
  <%= s.input :asisteescuela, 
    inline_label: "Asiste a Escuela",
    boolean_style: :nested
  %>
	<%= s.association :regimensalud,
		collection: Regimensalud.all.order(:nombre),
		include_blank: false,
		label: "Régimen de Salud",
		label_method: :nombre, 
		value_method: :id
  %>
  <%= s.input :eps, label: 'EPS o ARS' %>

  <%= s.input :tienesisben, 
    inline_label: "Tiene SISBEN",
    boolean_style: :nested
  %>

	<%= s.input :id_victima, as: :hidden %>
<% end %>

app/views/casos/_desplazamiento_fields.html.erb
<% #encoding: UTF-8 %>
<div class='control-group nested-fields'>
  <div class="controls">
    <%= f.input :id, as: :hidden %>
    <%= f.input :fechaexpulsion, 
      :input_html => { "data-behaviour" => "datepicker",
        value: f.object.fechaexpulsion || @caso.fecha },
        :as => :string
    %>
    <%= f.association :expulsion,
        collection: Ubicacion.where(:id_caso => @caso.id),
        label_method: lambda {|t| t.muestra(conclase: true) },
        value_method: :id 
    %>
    <%= f.input :fechallegada, 
          :input_html => { "data-behaviour" => "datepicker" },
          :as => :string
    %>
    <%= f.association :llegada,
          collection: Ubicacion.where(:id_caso => @caso.id),
          label_method: lambda {|t| t.muestra(conclase: true) },
          value_method: :id 
    %>
    <%= f.association :clasifdesp,
          collection: Clasifdesp.where(fechadeshabilitacion: nil),
          label_method: :nombre,
          value_method: :id 
    %>
    <%= f.association :tipodesp,
          collection: Tipodesp.where(fechadeshabilitacion: nil),
          label_method: :nombre,
          value_method: :id 
    %>
    <%= f.input :descripcion, as: :text %>
    <%= f.input :otrosdatos, as: :text %>
    <%= f.input :declaro, collection: [["SI", :S], 
      ["NO", :N], ["NO SABE / NO RESPONDE", :R]], 
      include_blank: false 
    %>
    <%= f.input :hechosdeclarados, as: :text %>
    <%= f.input :fechadeclaracion, 
          :input_html => { "data-behaviour" => "datepicker" },
          :as => :string
    %>
    <%= f.association :declaroante,
          collection: Declaroante.where(fechadeshabilitacion: nil),
          label_method: :nombre,
          value_method: :id 
    %>
    <%= f.association :inclusion,
          collection: Inclusion.where(fechadeshabilitacion: nil),
          label_method: :nombre,
          value_method: :id 
    %>
    <%= f.association :acreditacion,
          collection: Acreditacion.where(fechadeshabilitacion: nil),
          label_method: :nombre,
          value_method: :id 
    %>
    <%= f.input :retornado, 
        boolean_style: :nested,
        inline_label: Desplazamiento.human_attribute_name(:retornado)
    %>
    <%= f.input :reubicado, 
        boolean_style: :nested,
        inline_label: Desplazamiento.human_attribute_name(:reubicado)
    %>
    <%= f.input :connacionalretorno, 
        boolean_style: :nested,
        inline_label: Desplazamiento.human_attribute_name(:connacionalretorno)
    %>
    <%= f.input :acompestado, 
        boolean_style: :nested,
        inline_label: Desplazamiento.human_attribute_name(:acompestado)
    %>
    <%= f.input :connacionaldeportado, 
        boolean_style: :nested,
        inline_label: Desplazamiento.human_attribute_name(:connacionaldeportado)
    %>
    <%= f.input :oficioantes %>
    <%= f.association :modalidadtierra,
      collection: Modalidadtierra .where(fechadeshabilitacion: nil),
      label_method: :nombre,
      value_method: :id 
    %>
    <%= f.input :materialesperdidos, as: :text %>
    <%= f.input :inmaterialesperdidos, as: :text %>
    <%= f.input :protegiorupta, 
        boolean_style: :nested,
        inline_label: Desplazamiento.human_attribute_name(:protegiorupta)
    %>
    <%= f.input :documentostierra, as: :text %>

    <%= link_to_remove_association "Eliminar Desplazamiento", f, 
      {:class => 'btn-danger', :'data-existing' => 'true'} 
    %>
  </div>
</div>

app/views/casos/index.html.erb
<%- model_class = Caso -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table width="100%">
  <tr>
    <td width="33%">
      <% if @conscaso.size > 0 %>
        <%= link_to t('.new', :default => t("helpers.links.new")),
          new_caso_path,
          :class => 'btn btn-primary' 
        %>
      <% end %>
    </td>
    <td style="width=33%;text-align: center">
      Casos: <%= @numconscaso %>
    </td>
    <td style="text-align: right">
      <%= form_tag(casos_path, method: "get") do %>
        <%= text_field_tag(:q) %>
        <%= submit_tag("Filtrar") %>
      <% end %>
    </td>
  </tr>
</table>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= Caso.human_attribute_name(:id) %></th>
      <th><%= Casosjr.human_attribute_name(:contacto) %></th>
      <th><%= Casosjr.human_attribute_name(:fecharec) %></th>
      <th><%= Casosjr.human_attribute_name(:regionsjr) %></th>
      <th><%= Casosjr.human_attribute_name(:asesor) %></th>
      <th><%= "Fecha Desp. Emb." %></th>
      <th><%= "Mun. Expulsor D.E" %></th>
      <th><%= "Mun. Receptor D.E" %></th>
      <th><%= "Ult. Atencion" %></th>
      <th><%= Caso.human_attribute_name(:memo) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @conscaso.try(:each) do |casosjr| %>
      <tr>
        <td><%= link_to casosjr.caso_id, caso_path(casosjr.caso_id)  %></td>
        <td><%= casosjr.contacto_nombre %></td>
        <td><%= casosjr.fecharec %></td>
        <td><%= casosjr.regionsjr_nombre %></td>
        <td><%= casosjr.nusuario %></td>
        <td><%= casosjr.caso_fecha %></td>
        <td><%= casosjr.expulsion %></td>
        <td><%= casosjr.llegada %></td>
	      <td><%= casosjr.respuesta_ultimafechaatencion %></td>
        <td><%= casosjr.caso_memo %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_caso_path(casosjr.caso_id), :class => 'btn btn-xs' 
          %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            caso_path(casosjr.caso),
            :method => :delete,
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-xs btn-danger' 
          %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @conscaso, { param_name: :pagina }  %>
<%= link_to t('.new', :default => t("helpers.links.new")),
  new_caso_path,
  :class => 'btn btn-primary' 
%>